name: Releaser
permissions: write-all
defaults:
  run:
    shell: bash
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
env:
  APP_NAME: 'service.caradium'
on:
  push:
    tags:
    - '[0-9]+.[0-9]+.[0-9]+'
  workflow_dispatch:
    inputs:
      tag:
        description: 'The tag which will be released'
        required: true
        type: string

jobs:
  release:
    name: Release new version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
            fetch-depth: 0
            ref: ${{ inputs.tag || github.ref }}
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ inputs.tag || github.ref }}
          release_name: ${{ inputs.tag || github.ref }} Release
          draft: false
          prerelease: false
      - name: Upload Artifact
        id: upload_artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ github.workspace }}/builds/${{ env.APP_NAME }}.zip
          #asset_name: ${{ env.APP_NAME }}-${{ inputs.tag || github.ref_name }}.zip
          # Allow the latest zip file to be downloaded without knowing the version.
          asset_name: ${{ env.APP_NAME }}.zip
          asset_content_type: application/zip
